blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Extension Issue
      url: https://github.com/charithmadhuranga/filmpisso-extensions/issues/new/choose
      about: Issues and requests for extensions and sources should be opened in the filmpisso-extensions repository instead
  - name: ğŸ§‘â€ğŸ’» Filmpisso help discord
    url: https://discord.com/invite/EjfBuYahsP
    about: Common questions are answered here
